'use strict';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),RADIUS=11,JIM_WIDTH=44,JIM_BODY=40;
const art={},errors=[],keys={},floors={},discovered=new Set();
let W=innerWidth,H=innerHeight,dpr=1,zoom=1,clock=0,last=0,running=false,paused=false,mapOpen=false,modal=null,transition=null,activity=null,ended=false;
let walkAmount=0;let player,dog,state,camera,stick={x:0,y:0},pointer=null,stepTimer=0,phase=0,toastTimer=0,alarmTimer=0,stairCooldown=0;
const audio={context:null,master:null,buffers:{},voices:new Set(),muted:false,shower:null};
const soundNames=['door-open','door-close','switch',...['l','r'].flatMap(s=>[1,2,3].map(n=>'step-'+s+n)),...['l','r'].flatMap(s=>[1,2,3].map(n=>'step-carpet-'+s+n))];
function unlockAudio(){const A=globalThis.AudioContext||globalThis.webkitAudioContext;if(!A)return;if(!audio.context){const c=audio.context=new A();audio.master=c.createGain();audio.master.gain.value=.5;audio.master.connect(c.destination);Promise.all(soundNames.map(async n=>{try{const r=await fetch('assets/'+n+'.wav');if(!r.ok)return;audio.buffers[n]=await c.decodeAudioData(await r.arrayBuffer())}catch{}}));}audio.context.resume().catch(()=>{});}
function sample(n,v=.4,rate=1){const c=audio.context,b=audio.buffers[n];if(!c||!b||audio.muted||!active())return;const s=c.createBufferSource(),g=c.createGain();s.buffer=b;s.playbackRate.value=rate;g.gain.value=v;s.connect(g);g.connect(audio.master);audio.voices.add(s);s.onended=()=>{audio.voices.delete(s);s.disconnect();g.disconnect()};s.start();}
function tone(freq,duration=.15,delay=0){const c=audio.context;if(!c||audio.muted)return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.07,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(audio.master);audio.voices.add(o);o.onended=()=>{audio.voices.delete(o);o.disconnect();g.disconnect()};o.start(t);o.stop(t+duration);}
function reminder(){tone(784,.17);tone(1047,.2,.22);tone(784,.17,.49);}
function showerNoise(on){if(audio.shower){try{audio.shower.stop()}catch{}audio.shower=null;}const c=audio.context;if(!on||!c||audio.muted)return;const b=c.createBuffer(1,c.sampleRate*2,c.sampleRate),d=b.getChannelData(0);let sm=0;for(let i=0;i<d.length;i++){sm=.4*sm+.6*(Math.random()*2-1);d[i]=sm*.24}const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=b;s.loop=true;f.type='lowpass';f.frequency.value=4200;g.gain.value=.2;s.connect(f);f.connect(g);g.connect(audio.master);s.onended=()=>{s.disconnect();f.disconnect();g.disconnect()};s.start();audio.shower=s;}
function syncAudio(){if(!audio.context)return;const enabled=active()&&!audio.muted&&!document.hidden;audio.master.gain.setTargetAtTime(enabled?.5:0,audio.context.currentTime,.025);if(!enabled){for(const s of audio.voices){try{s.stop()}catch{}}}}
function rect(r,v){return{x:r.x+v[0]*r.w,y:r.y+v[1]*r.h,w:v[2]*r.w,h:v[3]*r.h};}
function point(r,v){return{x:r.x+v[0]*r.w,y:r.y+v[1]*r.h};}
function inside(b,x,y,p=0){return x>=b.x-p&&x<=b.x+b.w+p&&y>=b.y-p&&y<=b.y+b.h+p;}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function room(id,f=state.floor){return floors[f].rooms.find(r=>r.id===id);}
function buildFloors(){for(const [name,placements] of Object.entries(HOME_PLACEMENTS)){const f=floors[name]={rooms:[],walk:[],solids:[],links:[]};for(const [id,x,y]of placements){const c=HOME_CATALOGUE[id],r={id,x,y,w:c.width,h:c.width*c.ratio,c};f.rooms.push(r);f.walk.push(rect(r,c.floor));for(const b of c.solids)f.solids.push(rect(r,b));}
 for(const link of HOME_LINKS[name]||[]){const [a,ad,b,bd]=link,ra=f.rooms.find(r=>r.id===a),rb=f.rooms.find(r=>r.id===b),pa=point(ra,ra.c.doors[ad]),pb=point(rb,rb.c.doors[bd]);const vertical=ad==='north'||ad==='south',width=62;
 // Connections meet each room's artwork aperture. A narrow passage absorbs offsets.
 const mid=vertical?{x:pa.x,y:pb.y}:{x:pb.x,y:pa.y},segments=[];for(const [u,v]of [[pa,mid],[mid,pb]]){if(distance(u,v)<1)continue;segments.push({x:Math.min(u.x,v.x)-width/2,y:Math.min(u.y,v.y)-width/2,w:Math.abs(u.x-v.x)+width,h:Math.abs(u.y-v.y)+width});}
 for(const [r,p,d]of [[ra,pa,ad],[rb,pb,bd]]){const b=rect(r,r.c.floor);let q={x:Math.max(b.x+width/2,Math.min(b.x+b.w-width/2,p.x)),y:Math.max(b.y+width/2,Math.min(b.y+b.h-width/2,p.y))};segments.push({x:Math.min(p.x,q.x)-width/2,y:Math.min(p.y,q.y)-width/2,w:Math.abs(p.x-q.x)+width,h:Math.abs(p.y-q.y)+width});}
 f.walk.push(...segments);const horizontal=!vertical,gate={x:pa.x,y:pa.y,vertical:horizontal,w:width,open:false,progress:0,name:rb.c.name};f.links.push({a,b,segments,gate});}
 }}
function currentFloor(){return floors[state.floor];}
function doorBox(g){return g.vertical?{x:g.x-5,y:g.y-g.w/2,w:10,h:g.w*(1-g.progress)}:{x:g.x-g.w/2,y:g.y-5,w:g.w*(1-g.progress),h:10};}
function clear(x,y,radius=RADIUS,f=state.floor,ignoreDoors=false){const data=floors[f];for(let i=0;i<12;i++){const a=i*Math.PI/6,px=x+Math.cos(a)*radius,py=y+Math.sin(a)*radius;if(!data.walk.some(b=>inside(b,px,py)))return false;}if(data.solids.some(b=>inside(b,x,y,radius)))return false;if(f==='ground'&&!state.toiletOpen&&inside(rect(floors.ground.rooms.find(r=>r.id==='hall'),[.707,.18,.015,.145]),x,y,radius))return false;if(!ignoreDoors&&data.links.some(l=>l.gate.progress<.98&&inside(doorBox(l.gate),x,y,radius)))return false;return true;}
function move(o,dx,dy,r=RADIUS,f=state.floor){const n=Math.max(1,Math.ceil(Math.hypot(dx,dy)/4));for(let i=0;i<n;i++){if(clear(o.x+dx/n,o.y,r,f))o.x+=dx/n;if(clear(o.x,o.y+dy/n,r,f))o.y+=dy/n;}}
function findRoom(p=player,f=state.floor){return floors[f].rooms.find(r=>inside(rect(r,r.c.floor),p.x,p.y))||null;}
function discover(){const r=findRoom();if(r)discovered.add(state.floor+':'+r.id);for(const l of currentFloor().links)if(l.gate.progress>.6&&(discovered.has(state.floor+':'+l.a)||discovered.has(state.floor+':'+l.b))){discovered.add(state.floor+':'+l.a);discovered.add(state.floor+':'+l.b);}}
function resetInput(){stick={x:0,y:0};pointer=null;for(const k in keys)delete keys[k];$('#knob').style.transform='';}
function active(){return running&&!paused&&!mapOpen&&!modal&&!ended;}
function say(t,seconds=5){$('#toast').textContent=t;toastTimer=seconds;}
function setOverlay(title,text,button,kind){resetInput();modal=kind;$('#title').textContent=title;$('#intro').textContent=text;$('#start').textContent=button;$('#overlay').style.display='flex';document.body.classList.add('covered');}
function closeOverlay(){modal=null;$('#overlay').style.display='none';document.body.classList.remove('covered');}
function reset(){state={floor:'upper',outfit:'blur',inBed:true,towel:false,showered:false,dressed:false,breakfast:false,note:false,alarm:false};discovered.clear();discovered.add('upper:bedroom');const r=room('bedroom','upper'),p=point(r,r.c.actions.bed);player={...p,angle:0,health:80};dog={x:0,y:0,angle:0,floor:'ground',target:null,path:[],wait:0,walk:0};const lr=room('lounge','ground');Object.assign(dog,point(lr,lr.c.actions.dogBed));camera={x:player.x,y:player.y};for(const f of Object.values(floors))for(const l of f.links)Object.assign(l.gate,{open:false,progress:0});ended=false;paused=false;mapOpen=false;activity=null;transition=null;alarmTimer=0;stairCooldown=0;stepTimer=0;phase=0;clock=0;resetInput();hud();}
function start(){if(errors.length)return;unlockAudio();reset();running=true;closeOverlay();say('Move the left stick to get out of bed.');}
function task(){if(state.inBed)return 'Wake up · move to get out of bed';if(!state.towel)return 'Pick up the white towel beside the bed · USE';if(!state.showered)return 'Have a shower in the bathroom';if(!state.dressed)return 'Get dressed at the bedroom wardrobe';if(!state.breakfast)return 'Get breakfast in the kitchen';if(!state.note)return 'Find Emma’s note on the dining table';if(!state.alarm)return 'Emma will be back later · explore Home';return 'Time for work · enter the yellow Vivaro';}
function hud(){const r=findRoom();$('#location').textContent='DEAD SIGNAL · HOME / '+(r?r.c.name:state.floor==='upper'?'First floor':state.floor==='ground'?'Ground floor':'Outside');$('#objective').textContent=task();$('#healthValue').textContent=player.health;$('#healthFill').style.width=player.health+'%';$('#mapButton').textContent=mapOpen?'CLOSE MAP':'MAP';const t=nearby();$('#useHint').textContent=t?t.label:'Nearby interaction';}
function interactions(){const a=[];function add(id,label,r,p,approach,fn,range=48){a.push({id,label,room:r.id,position:point(r,p),approach:point(r,approach||p),fn,range});}
 if(state.floor==='upper'){const b=room('bedroom'),ba=room('bathroom');if(!state.towel&&!state.inBed)add('towel','Pick up towel',b,b.c.actions.towel,null,()=>{state.towel=true;state.outfit='towel';say('Towel wrapped. Head to the bathroom for a shower.');sample('switch',.2);});add('wardrobe','Get dressed',b,b.c.actions.wardrobe,null,()=>{if(!state.showered){say('Have a shower before getting dressed.');return;}if(state.dressed){say('Already dressed for the day.');return;}activity={type:'dress',time:1.2,total:1.2};resetInput();});add('shower','Have a shower',ba,ba.c.actions.shower,null,()=>{if(!state.towel){say('Pick up your towel first.');return;}if(state.showered){say('Shower done. Time to get dressed.');return;}activity={type:'shower',time:4.5,total:4.5,returnPosition:{x:player.x,y:player.y}};Object.assign(player,point(ba,ba.c.actions.showerInside));resetInput();showerNoise(true);});}
 if(state.floor==='ground'){const k=room('kitchen'),h=room('hall'),g=room('garage');if(dog.floor===state.floor&&distance(player,dog)<55)a.push({id:'bella',label:'Pet Bella',room:(findRoom(dog)||{id:'lounge'}).id,position:dog,approach:dog,range:45,fn:()=>{dog.wait=2;dog.path=[];say('Bella wags her tail.');}});if(!state.breakfast)add('breakfast','Have breakfast',k,k.c.actions.breakfast,k.c.actions.breakfastApproach,()=>{if(!state.dressed){say('Get dressed before breakfast.');return;}state.breakfast=true;player.health=100;tone(660);tone(880,.2,.14);say('Breakfast · +20 HEALTH. Find Emma’s note on the table.');});add('note','Read Emma’s note',k,k.c.actions.note,k.c.actions.noteApproach,()=>{if(!state.dressed){say('Get dressed upstairs first.');return;}state.note=true;setOverlay('A NOTE FROM EMMA','Jim,\n\nI’ve managed to get a meeting with the head of the research facility. I’ll explain when I’m home—it’s easier in person. Should be back later.\n\nThere’s breakfast ready in the kitchen.\n\nLove, Emma x','Close note','note');});add('front','Open front door',h,h.c.actions.frontDoor,[.555,.84],()=>leaveHouse('front'));add('garage','Open garage door',g,g.c.actions.garageDoor,[.5,.85],()=>leaveHouse('garage'));add('toilet','Use toilet door',h,h.c.actions.toilet,[.671,.26],()=>{state.toiletOpen=!state.toiletOpen;say(state.toiletOpen?'Downstairs toilet door open.':'Downstairs toilet door closed.');sample(state.toiletOpen?'door-open':'door-close',.3);});}
 if(state.floor==='outside'){const d=room('driveway');add('van','Enter Vivaro',d,d.c.actions.van,null,()=>{if(!state.alarm){say('Finish your morning routine first.');return;}transitionTo('end',null);});add('home','Open front door',d,d.c.actions.frontDoor,[.44,.175],()=>transitionTo('ground',point(room('hall','ground'),[.555,.835])));add('garage','Open garage door',d,d.c.actions.garageDoor,[.71,.177],()=>transitionTo('ground',point(room('garage','ground'),[.5,.835])));}
 return a;
}
function nearby(){if(!player||state.inBed||activity||transition)return null;const a=interactions().filter(t=>discovered.has(state.floor+':'+t.room)&&distance(player,t.approach)<t.range);for(const l of currentFloor().links)if(distance(player,l.gate)<60&&(discovered.has(state.floor+':'+l.a)||discovered.has(state.floor+':'+l.b)))a.push({id:'door',label:(l.gate.open?'Close ':'Open ')+l.gate.name,approach:l.gate,fn:()=>{if(l.gate.open&&distance(player,l.gate)<RADIUS+12){say('Step clear of the doorway to close it.');return;}l.gate.open=!l.gate.open;sample(l.gate.open?'door-open':'door-close',.35);}});return a.sort((a,b)=>distance(player,a.approach)-distance(player,b.approach))[0]||null;}
function use(){if(!active()||activity||transition)return;unlockAudio();const t=nearby();if(t)t.fn();else say('Move beside an object or doorway, then press USE.',2.5);hud();}
function leaveHouse(which){if(!state.alarm){say('Finish your morning routine before leaving for work.');return;}sample('door-open');const d=room('driveway','outside');transitionTo('outside',point(d,which==='front'?[.44,.185]:[.71,.18]));}
function transitionTo(f,p){if(transition)return;resetInput();transition={to:f,point:p,time:0,changed:false};}
function stairCheck(){if(stairCooldown>0||activity||transition)return;if(state.floor==='upper'){const r=room('landing'),p=point(r,r.c.actions.stairs);if(distance(player,p)<24)transitionTo('ground',point(room('hall','ground'),HOME_CATALOGUE.hall.actions.stairSpawn));}else if(state.floor==='ground'){const r=room('hall'),p=point(r,r.c.actions.stairs);if(distance(player,p)<26)transitionTo('upper',point(room('landing','upper'),HOME_CATALOGUE.landing.actions.stairSpawn));}}
function updateTransition(dt){if(!transition)return;transition.time+=dt;if(transition.time>=.22&&!transition.changed){transition.changed=true;if(transition.to==='end'){ended=true;setOverlay('OFF TO WORK','Jim gets into his yellow Vivaro and drives to the police station.\n\nHome morning play test complete. Emma’s note is still on the kitchen table.\n\nThe police station is the next area to build.','Play Home again','end');}else{state.floor=transition.to;Object.assign(player,transition.point);camera={x:player.x,y:player.y};stairCooldown=1.2;discover();}}if(transition.time>=.45)transition=null;}
function toggleMap(){if(!running||modal||paused||activity||transition||ended)return;mapOpen=!mapOpen;resetInput();document.body.classList.toggle('covered',mapOpen);document.body.classList.toggle('map-open',mapOpen);hud();}
function pause(){if(!running||ended||activity||transition)return;if(mapOpen){toggleMap();return;}if(modal){closeOverlay();return;}paused=!paused;if(paused)setOverlay('PAUSED','Take a breather. Your place in Home is saved until you restart this play test.','Resume','pause');else closeOverlay();}
const dogNav=new Map();let dogNavKey='';
function gridPath(from,to,f){const navKey=f+':'+floors[f].links.map(l=>l.gate.progress>=.98?1:0).join('')+':'+Boolean(state.toiletOpen);if(navKey!==dogNavKey){dogNav.clear();dogNavKey=navKey;}const step=16,round=p=>({x:Math.round(p.x/step),y:Math.round(p.y/step)}),s=round(from),t=round(to),key=p=>p.x+','+p.y,q=[s],prev=new Map([[key(s),null]]);let found=null;for(let i=0;i<q.length&&i<12000;i++){const p=q[i];if(Math.abs(p.x-t.x)+Math.abs(p.y-t.y)<=1){found=p;break;}for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,y:p.y+dy},k=key(n);if(!dogNav.has(k))dogNav.set(k,clear(n.x*step,n.y*step,8,f));if(!prev.has(k)&&dogNav.get(k)){prev.set(k,p);q.push(n);}}}if(!found)return[];const path=[];for(let p=found;prev.get(key(p));p=prev.get(key(p)))path.push({x:p.x*step,y:p.y*step});return path.reverse();}
function updateDog(dt){if(state.floor!==dog.floor)return;dog.wait-=dt;dog.walk=0;if(dog.wait>0)return;if(!dog.path.length){let target;if(distance(player,dog)<36){target={x:dog.x+(dog.x-player.x)*2,y:dog.y+(dog.y-player.y)*2};}else if(distance(player,dog)<170&&!activity&&Math.random()<.5){target={x:player.x-40,y:player.y+25};}else{const f=floors[dog.floor],known=f.rooms.filter(r=>discovered.has(dog.floor+':'+r.id));const r=known[Math.floor(Math.random()*known.length)]||room('lounge','ground'),b=rect(r,r.c.floor);for(let i=0;i<30;i++){const p={x:b.x+20+Math.random()*(b.w-40),y:b.y+20+Math.random()*(b.h-40)};if(clear(p.x,p.y,9,dog.floor)){target=p;break;}}}if(target)dog.path=gridPath(dog,target,dog.floor);if(!dog.path.length){dog.wait=1+Math.random()*2;return;}}
 const t=dog.path[0],d=distance(dog,t);if(d<5){dog.path.shift();if(!dog.path.length)dog.wait=1+Math.random()*4;return;}if(!clear(t.x,t.y,8,dog.floor)){dog.path=[];dog.wait=.5;return;}dog.angle=Math.atan2(t.y-dog.y,t.x-dog.x)+Math.PI/2;const before={x:dog.x,y:dog.y};move(dog,(t.x-dog.x)/d*48*dt,(t.y-dog.y)/d*48*dt,8,dog.floor);dog.walk=distance(before,dog);if(dog.walk<.05)dog.path=[];
}
function update(dt){walkAmount=0;clock+=dt;stairCooldown=Math.max(0,stairCooldown-dt);updateTransition(dt);if(transition||ended){hud();return;}for(const l of currentFloor().links){const g=l.gate;if(!g.open&&g.progress>0&&(inside(doorBox(g),player.x,player.y,RADIUS+4)||(dog.floor===state.floor&&inside(doorBox(g),dog.x,dog.y,12))))g.open=true;g.progress=Math.max(0,Math.min(1,g.progress+(g.open?1:-1)*dt*2.7));}
 if(activity){activity.time-=dt;if(activity.time<=0){if(activity.type==='shower'){showerNoise(false);state.showered=true;Object.assign(player,activity.returnPosition);say('Shower done. Get dressed at your bedroom wardrobe.');}else{state.dressed=true;state.outfit='dressed';say('Black vest, jeans and flip-flops. Head downstairs for breakfast.');}activity=null;}hud();return;}
 let x=stick.x+(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),y=stick.y+(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),n=Math.hypot(x,y);if(n>.05){if(state.inBed){state.inBed=false;Object.assign(player,point(room('bedroom'),HOME_CATALOGUE.bedroom.actions.bedExit));say('Pick up the white towel beside the bed with USE.');}else{if(n>1){x/=n;y/=n;}player.angle=Math.atan2(y,x)+Math.PI/2;const b={x:player.x,y:player.y};move(player,x*105*dt,y*105*dt);const d=distance(b,player);walkAmount=d;phase+=d*.13;stepTimer-=dt;if(d>.1&&stepTimer<=0){const r=findRoom(),tile=r&&(r.c.surface==='tile'||r.c.surface==='concrete'||r.c.surface==='outside'||(r.id==='kitchen'&&player.x<r.x+r.w*.54));sample('step-'+(tile?'':'carpet-')+(Math.sin(phase)>0?'l':'r')+(1+Math.floor(Math.random()*3)),state.outfit==='dressed'?.13:.09,tile?.95:1.08);stepTimer=.34;}}}
 discover();stairCheck();updateDog(dt);if(state.note&&state.breakfast&&state.dressed&&!state.alarm){alarmTimer+=dt;if(alarmTimer>1.8){state.alarm=true;reminder();say('Your phone reminder: time to leave for work. Enter the yellow Vivaro.',8);}}hud();}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;zoom=Math.min(2.4,Math.max(1.35,Math.min((W-290)/450,(H-130)/340)));}
function rounded(x,y,w,h,r=5){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function drawOak(b){ctx.save();ctx.beginPath();ctx.rect(b.x,b.y,b.w,b.h);ctx.clip();for(let x=b.x;x<b.x+b.w;x+=28)for(let y=b.y;y<b.y+b.h;y+=28)ctx.drawImage(art[state.floor==='ground'?'hall':'bedroom'],state.floor==='ground'?555:805,state.floor==='ground'?1050:825,85,85,x,y,28,28);ctx.restore();}
function drawConnections(){for(const l of currentFloor().links){if(!discovered.has(state.floor+':'+l.a)&&!discovered.has(state.floor+':'+l.b))continue;for(const b of l.segments){drawOak(b);}}}
function drawDoors(){for(const l of currentFloor().links){if(!discovered.has(state.floor+':'+l.a)&&!discovered.has(state.floor+':'+l.b))continue;const g=l.gate,b=doorBox(g);ctx.fillStyle='#d8c6a6';ctx.strokeStyle='#66583f';ctx.lineWidth=2;if(b.w>0&&b.h>0){ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeRect(b.x,b.y,b.w,b.h);}ctx.fillStyle='#a68a52';ctx.beginPath();ctx.arc(g.x+(g.vertical?0:-g.w/2+9),g.y+(g.vertical?-g.w/2+9:0),2.3,0,Math.PI*2);ctx.fill();}}
function drawItem(t){if(!discovered.has(state.floor+':'+t.room))return;const p=t.position;ctx.save();ctx.translate(p.x,p.y);const blink=.55+.45*Math.pow(Math.max(0,Math.sin(clock*4)),5);if((t.id==='note'&&!state.note)||t.id==='towel'||t.id==='breakfast'){ctx.shadowColor='#fff1b6';ctx.shadowBlur=12*blink;}
 if(t.id==='note'){ctx.rotate(-.12);ctx.fillStyle=state.note?'#e6dcc6':`rgba(255,250,222,${blink})`;ctx.fillRect(-6,-8,12,16);ctx.shadowBlur=0;ctx.fillStyle='#7b766b';for(let i=0;i<4;i++)ctx.fillRect(-3,-4+i*2,6,1);}else if(t.id==='towel'){ctx.rotate(.2);ctx.fillStyle='#fffaf1';rounded(-10,-5,20,11,3);ctx.fill();ctx.strokeStyle='#c9c4bd';ctx.beginPath();ctx.moveTo(-6,-2);ctx.lineTo(7,-2);ctx.stroke();}else if(t.id==='breakfast'){ctx.fillStyle='#f4eadc';ctx.beginPath();ctx.arc(0,0,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b77b36';rounded(-4,-4,8,8,2);ctx.fill();}ctx.restore();}
// Torso art and feet are separate render passes. Every outfit uses identical dimensions.
// Feet are drawn anatomically facing north in local space, then rotate with Jim.
const SPRITES={dressed:{asset:'jim-dressed',body:[0,0,865,605]},towel:{asset:'jim-towel',body:[0,0,930,865]}};
function drawJim(){if(state.inBed){const r=room('bedroom'),p=point(r,[.48,.16]);ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='#bf8967';ctx.beginPath();ctx.ellipse(0,0,7,8.5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6b5b50';ctx.beginPath();ctx.ellipse(0,-3,6,5,0,0,Math.PI*2);ctx.fill();ctx.restore();return;}
 const sp=SPRITES[state.outfit==='dressed'?'dressed':'towel'],im=art[sp.asset];ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.fillStyle='#00000025';ctx.beginPath();ctx.ellipse(0,5,18,13,0,0,Math.PI*2);ctx.fill();for(let i=0;i<2;i++){const sx=i?8:-8,sy=18+(walkAmount>.05?Math.sin(phase+(i?Math.PI:0))*4:0);ctx.save();ctx.translate(sx,sy);if(state.outfit==='dressed'){ctx.fillStyle='#253850';rounded(-3.5,-7,7,13,3);ctx.fill();}ctx.fillStyle='#c98d6c';ctx.beginPath();ctx.ellipse(0,0,3,5.7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#deb093';for(let j=0;j<4;j++){ctx.beginPath();ctx.arc(-2+j*1.3,-4.5,1.1,0,Math.PI*2);ctx.fill();}if(state.outfit==='dressed'){ctx.strokeStyle='#243d59';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(-3,-2);ctx.lineTo(0,-4);ctx.lineTo(3,-2);ctx.stroke();}ctx.restore();}const [bx,by,bw,bh]=sp.body;const swing=walkAmount>.05?Math.sin(phase)*2:Math.sin(clock*1.7)*.15;ctx.drawImage(im,bx+bw*.22,by,bw*.56,bh,-JIM_WIDTH*.28,-24,JIM_WIDTH*.56,JIM_BODY);ctx.drawImage(im,bx,by,bw*.22,bh,-JIM_WIDTH/2,-24+swing,JIM_WIDTH*.22,JIM_BODY);ctx.drawImage(im,bx+bw*.78,by,bw*.22,bh,JIM_WIDTH*.28,-24-swing,JIM_WIDTH*.22,JIM_BODY);
 if(state.outfit==='blur'||(activity&&activity.type==='shower')){ctx.save();ctx.fillStyle='#d0c7baff';ctx.shadowColor='#ded6caff';ctx.shadowBlur=5;rounded(-17,2,34,20,6);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#b5b2a9';for(let i=0;i<6;i++){ctx.globalAlpha=.2;ctx.fillRect(-14+i*4,6+(i%2)*4,9,9);}ctx.restore();}ctx.restore();}
function drawDog(){if(dog.floor!==state.floor)return;const r=findRoom(dog,dog.floor);if(r&&!discovered.has(dog.floor+':'+r.id))return;ctx.save();ctx.translate(dog.x,dog.y);ctx.rotate(dog.angle);const im=art.collie,gait=dog.walk>.05?Math.sin(clock*10)*2:0;ctx.save();ctx.translate(0,17);ctx.rotate(Math.sin(clock*4)*.17);ctx.drawImage(im,360,1170,280,340,-6,0,12,15);ctx.restore();for(let i=0;i<4;i++){const x=i%2?10:-10,y=i<2?-6:12;ctx.save();ctx.translate(x,y+gait*(i===0||i===3?1:-1));ctx.drawImage(im,i%2?620:337,i<2?650:1060,65,90,-2,-2,4,6);ctx.restore();}ctx.save();ctx.rotate(dog.walk>.05?Math.sin(clock*10)*.02:Math.sin(clock*1.5)*.008);ctx.drawImage(im,225,95,560,1110,-12,-28,24,48);ctx.restore();ctx.restore();}
function drawShower(){if(!activity||activity.type!=='shower')return;ctx.save();ctx.translate(player.x,player.y);ctx.fillStyle='#e8eef0e8';ctx.shadowColor='#fff';ctx.shadowBlur=12;ctx.beginPath();ctx.ellipse(0,0,32,35,0,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#c7e4eeaa';ctx.lineWidth=1.5;for(let i=0;i<14;i++){const x=(i*13%55)-27,y=((clock*75+i*19)%65)-32;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-2,y+8);ctx.stroke();}ctx.restore();}
function worldDraw(){ctx.fillStyle='#19232b';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2,H/2);ctx.scale(zoom,zoom);ctx.translate(-camera.x,-camera.y);drawConnections();for(const r of currentFloor().rooms){if(!discovered.has(state.floor+':'+r.id))continue;ctx.drawImage(art[r.c.image],r.x,r.y,r.w,r.h);}drawConnections(); // Repaint connection apertures after art so margins cannot cover a route.
 for(const l of currentFloor().links){const a=room(l.a),b=room(l.b);for(const [r,d]of [[a,HOME_LINKS[state.floor].find(v=>v[0]===l.a&&v[2]===l.b)[1]],[b,HOME_LINKS[state.floor].find(v=>v[0]===l.a&&v[2]===l.b)[3]]]){if(!discovered.has(state.floor+':'+r.id))continue;const p=point(r,r.c.doors[d]);if(d==='north'||d==='south')drawOak({x:p.x-28,y:p.y-7,w:56,h:14});else drawOak({x:p.x-7,y:p.y-28,w:14,h:56});}}
 drawDoors();for(const t of interactions())drawItem(t);drawDog();drawJim();drawShower();if(activity){ctx.fillStyle='#101921bb';rounded(player.x-35,player.y+29,70,7,3);ctx.fill();ctx.fillStyle='#b3d1c0';ctx.fillRect(player.x-33,player.y+31,66*(1-activity.time/activity.total),3);}ctx.restore();}
function mapDraw(){ctx.fillStyle='#101921';ctx.fillRect(0,0,W,H);const f=currentFloor(),rs=f.rooms,minX=Math.min(...rs.map(r=>r.x)),minY=Math.min(...rs.map(r=>r.y)),maxX=Math.max(...rs.map(r=>r.x+r.w)),maxY=Math.max(...rs.map(r=>r.y+r.h)),s=Math.min((W-350)/(maxX-minX),(H-190)/(maxY-minY));ctx.save();ctx.translate((W-(maxX-minX)*s)/2,(H-(maxY-minY)*s)/2+30);ctx.scale(s,s);ctx.translate(-minX,-minY);for(const l of f.links){if(!discovered.has(state.floor+':'+l.a)&&!discovered.has(state.floor+':'+l.b))continue;ctx.fillStyle='#344654';for(const b of l.segments)ctx.fillRect(b.x,b.y,b.w,b.h);}for(const r of rs){if(!discovered.has(state.floor+':'+r.id))continue;ctx.fillStyle='#293c4a';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle='#7d939f';ctx.lineWidth=2/s;ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.fillStyle='#d9e4e9';ctx.font=14/s+'px system-ui';ctx.textAlign='center';ctx.fillText(r.c.name,r.x+r.w/2,r.y+r.h/2);}ctx.fillStyle='#86d7ec';ctx.beginPath();ctx.arc(player.x,player.y,7/s,0,Math.PI*2);ctx.fill();ctx.restore();ctx.fillStyle='#ead8b4';ctx.font='20px system-ui';ctx.textAlign='center';ctx.fillText('HOME · '+(state.floor==='upper'?'FIRST FLOOR':state.floor==='ground'?'GROUND FLOOR':'OUTSIDE'),W/2,110);ctx.font='14px system-ui';ctx.fillText('Explored rooms · MAP closes this view',W/2,H-45);}
function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);if(!player||!art.bedroom)return;if(mapOpen)mapDraw();else worldDraw();if(transition){const alpha=transition.time<.22?transition.time/.22:Math.max(0,1-(transition.time-.22)/.23);ctx.fillStyle='rgba(8,13,18,'+alpha+')';ctx.fillRect(0,0,W,H);}}
function bindTap(id,fn){const e=$(id);e.onpointerdown=v=>{if(v.pointerType==='mouse'&&v.button!==0)return;v.preventDefault();if(!e.disabled)fn();};e.onclick=v=>{if(v.detail===0&&!e.disabled)fn();};e.oncontextmenu=v=>v.preventDefault();}
bindTap('#use',use);bindTap('#mapButton',toggleMap);bindTap('#pause',pause);bindTap('#soundButton',()=>{unlockAudio();audio.muted=!audio.muted;$('#soundButton').textContent=audio.muted?'SOUND OFF':'SOUND ON';$('#soundButton').setAttribute('aria-pressed',String(audio.muted));if(activity&&activity.type==='shower')showerNoise(!audio.muted);syncAudio();});bindTap('#start',()=>{unlockAudio();if(modal==='pause'){paused=false;closeOverlay();}else if(modal==='note'){closeOverlay();say(state.breakfast?'Emma will be back later.':'Have breakfast before heading out.');}else start();});
const se=$('#stick');function stickMove(e){const r=se.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,n=Math.hypot(x,y),rad=r.width*.35,strength=n<7?0:Math.min(1,n/rad);stick={x:n?x/n*strength:0,y:n?y/n*strength:0};$('#knob').style.transform='translate('+stick.x*rad+'px,'+stick.y*rad+'px)';}se.onpointerdown=e=>{if(!active()||activity||transition||pointer!==null)return;e.preventDefault();unlockAudio();pointer=e.pointerId;se.setPointerCapture(pointer);stickMove(e);};se.onpointermove=e=>{if(e.pointerId===pointer)stickMove(e);};se.onpointerup=se.onpointercancel=se.onlostpointercapture=e=>{if(e.pointerId===pointer)resetInput();};
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(e.repeat&&['e','m','escape'].includes(k))return;if(k==='e')use();else if(k==='m')toggleMap();else if(k==='escape'){if(modal==='pause'){paused=false;closeOverlay();}else pause();}else keys[k]=true;});addEventListener('keyup',e=>delete keys[e.key.toLowerCase()]);addEventListener('resize',resize);addEventListener('blur',()=>{resetInput();if(active()&&!activity&&!transition)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){resetInput();if(active()&&!activity&&!transition)pause();}syncAudio();});for(const t of ['gesturestart','gesturechange','gestureend','dblclick'])document.addEventListener(t,e=>e.preventDefault(),{passive:false});
async function loadArt(){const names=[...new Set(Object.values(HOME_CATALOGUE).map(r=>r.image)),'jim-dressed','jim-towel','collie'];await Promise.all(names.map(n=>new Promise(resolve=>{const im=new Image();im.onload=()=>{art[n]=im;resolve();};im.onerror=()=>{errors.push(n);resolve();};im.src='assets/home-'+n+'-v15.webp';})));$('#start').disabled=errors.length>0;$('#start').textContent=errors.length?'Missing artwork — check assets':'Start Home';if(errors.length)$('#intro').textContent='Could not load: '+errors.join(', ')+'. Upload all files in the ZIP’s assets folder into your GitHub assets folder, then reload.';}
function frame(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;if(active()&&!document.hidden)update(dt);if(player&&!mapOpen){const a=1-Math.exp(-dt*9);camera.x+=(player.x-camera.x)*a;camera.y+=(player.y-camera.y)*a;}if(toastTimer>0&&active()){toastTimer-=dt;if(toastTimer<=0)$('#toast').textContent='';}syncAudio();draw();requestAnimationFrame(frame);}
buildFloors();resize();reset();loadArt();requestAnimationFrame(frame);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
