'use strict';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d');const TILE=64;let W=innerWidth,H=innerHeight,zoom=1,last=0,clock=0,running=false,paused=false,mapOpen=false,stage=0,kills=0,cooldown=0,reloadTime=0,emptyPrompt=false,toastTime=0,player,creatures=[],bullets=[],hits=[],explored=new Set(),keys={},stick={x:0,y:0},firing=false;
const rooms=[{name:'AIRLOCK / START',x:1,y:23,w:7,h:5},{name:'RECEPTION',x:2,y:16,w:6,h:5},{name:'SECURITY',x:2,y:9,w:7,h:5},{name:'POWER ROOM',x:9,y:1,w:9,h:6},{name:'LABORATORY',x:29,y:1,w:9,h:6},{name:'CONTAINMENT',x:36,y:9,w:8,h:5},{name:'COMMS',x:28,y:17,w:6,h:5},{name:'LANDING PAD',x:37,y:24,w:8,h:5}];
const corridors=[[4,20,2,4],[4,13,2,4],[8,10,29,3],[12,6,2,5],[32,6,2,5],[17,3,13,2],[26,12,2,8],[27,18,2,2],[33,19,7,2],[38,20,2,5]];const floor=new Set();function carve(x,y,w,h){for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)floor.add(i+','+j)}rooms.forEach(r=>carve(r.x,r.y,r.w,r.h));corridors.forEach(r=>carve(...r));const doors=[
{name:'Reception',x:4,y:21,w:2,h:1,unlock:0,opened:false},
{name:'Security',x:4,y:14,w:2,h:1,unlock:0,opened:false},
{name:'Power room',x:12,y:8,w:2,h:1,unlock:0,opened:false},
{name:'Laboratory',x:32,y:8,w:2,h:1,unlock:2,opened:false},
{name:'Service passage',x:23,y:3,w:1,h:2,unlock:3,opened:false},
{name:'Containment',x:36,y:10,w:1,h:3,unlock:2,opened:false},
{name:'Communications',x:26,y:16,w:2,h:1,unlock:3,opened:false},
{name:'Extraction',x:38,y:23,w:2,h:1,unlock:4,opened:false}
];
const obstacles=[
{x:2,y:24,w:1,h:2,label:'CRATE'},
{x:2,y:17,w:2,h:1,label:'DESK'},{x:6,y:19,w:1,h:1,label:'CRATE'},
{x:3,y:10,w:1,h:2,label:'DESK'},{x:7,y:12,w:1,h:1,label:'CRATE'},
{x:10,y:2,w:1,h:2,label:'GENERATOR'},{x:15,y:5,w:2,h:1,label:'CRATE'},
{x:18,y:10,w:1,h:1,label:'CRATE'},{x:24,y:12,w:1,h:1,label:'CRATE'},
{x:31,y:3,w:1,h:2,label:'BENCH'},{x:35,y:2,w:2,h:1,label:'BENCH'},
{x:39,y:11,w:2,h:1,label:'TANK'},{x:42,y:10,w:1,h:1,label:'CRATE'},
{x:29,y:20,w:1,h:1,label:'DESK'},{x:32,y:18,w:1,h:1,label:'CRATE'},
{x:42,y:25,w:2,h:1,label:'CRATE'}
];
function inside(o,x,y,pad=0){return x>=o.x*TILE-pad&&x<(o.x+o.w)*TILE+pad&&y>=o.y*TILE-pad&&y<(o.y+o.h)*TILE+pad}
function rectDistance(o,a){let x=Math.max(o.x*TILE,Math.min(a.x,(o.x+o.w)*TILE)),y=Math.max(o.y*TILE,Math.min(a.y,(o.y+o.h)*TILE));return Math.hypot(a.x-x,a.y-y)}
function nearbyDoor(){return doors.filter(d=>rectDistance(d,player)<85).sort((a,b)=>rectDistance(a,player)-rectDistance(b,player))[0]}
function lockReason(d){return d.unlock===2?'Restore power first.':d.unlock===3?'Recover the laboratory keycard first.':'Restore communications first.'}

const objectives=[{x:5.5*TILE,y:11.5*TILE,label:'Access security terminal'},{x:13.5*TILE,y:3.5*TILE,label:'Restore power'},{x:33.5*TILE,y:3.5*TILE,label:'Recover laboratory data and keycard'},{x:31*TILE,y:19.5*TILE,label:'Restore communications'},{x:41*TILE,y:26.5*TILE,label:'Reach extraction'}];
function resize(){W=innerWidth;H=innerHeight;let d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*d);canvas.height=Math.round(H*d);ctx.setTransform(d,0,0,d,0,0);zoom=Math.max(.55,Math.min(.95,W/1250))}addEventListener('resize',resize);resize();
function open(x,y,ignoreDoor=false){const k=Math.floor(x/TILE)+','+Math.floor(y/TILE);return floor.has(k)&&(ignoreDoor||(!obstacles.some(o=>inside(o,x,y))&&!doors.some(d=>!d.opened&&inside(d,x,y))))}function clear(x,y,r){return [[-r,-r],[-r,r],[r,-r],[r,r]].every(([a,b])=>open(x+a,y+b))}function move(o,dx,dy){if(clear(o.x+dx,o.y,o.r))o.x+=dx;if(clear(o.x,o.y+dy,o.r))o.y+=dy}const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);function sight(a,b){let d=distance(a,b);for(let i=0;i<d;i+=12)if(!open(a.x+(b.x-a.x)*i/d,a.y+(b.y-a.y)*i/d))return false;return true}
function say(s){$('#toast').textContent=s;toastTime=3.5}function enemy(x,y,i){return{x:x*TILE,y:y*TILE,r:15,hp:3,angle:0,attack:0,active:false,think:0,target:null,speed:82+i%3*12}}
function reset(){player={x:4.5*TILE,y:25.5*TILE,r:16,angle:-Math.PI/2,hp:100,invuln:0,ammo:12};stage=0;pointer=null;firePointer=null;doors.forEach(d=>d.opened=false);kills=0;cooldown=0;reloadTime=0;emptyPrompt=false;clock=0;bullets=[];hits=[];explored=new Set();keys={};stick={x:0,y:0};firing=false;$('#fire').classList.remove('active');$('#mapButton').textContent='MAP';document.body.classList.remove('map-open');$('#knob').style.transform='';creatures=[[5,17],[6,10],[12,4],[16,4],[22,11],[30,4],[35,5],[39,10],[41,12],[30,18],[38,20],[40,26]].map((a,i)=>enemy(a[0]+.5,a[1]+.5,i));reveal()}
function reveal(){let px=Math.floor(player.x/TILE),py=Math.floor(player.y/TILE);for(let y=py-5;y<=py+5;y++)for(let x=px-5;x<=px+5;x++){let cell={x:(x+.5)*TILE,y:(y+.5)*TILE};if(distance(player,cell)<5*TILE&&open(cell.x,cell.y,true)&&sight(player,cell))explored.add(x+','+y)}}
function start(){reset();running=true;paused=false;mapOpen=false;$('#overlay').style.display='none';document.body.classList.remove('covered');say('Move with the left stick. Press USE near doors. Fire forward.');updateHUD()}
function updateHUD(){$('#stats').textContent='HEALTH '+Math.max(0,Math.ceil(player.hp))+'   MAG '+player.ammo+'/12 · RESERVE ∞   KILLS '+kills+'/12';$('#objective').textContent=(stage+1)+' / '+(objectives[stage]?.label||'Extraction complete');$('#reload').textContent=reloadTime>0?'LOADING '+reloadTime.toFixed(1):'RELOAD';$('#reload').disabled=reloadTime>0||player.ammo===12;const d=nearbyDoor();const o=objectives[stage];$('#use').textContent=o&&distance(player,o)<100?'USE':d?(stage<d.unlock?'LOCKED':d.opened?'CLOSE':'OPEN'):'USE'}
function toggleMap(){if(!running||paused)return;mapOpen=!mapOpen;firing=false;stick={x:0,y:0};keys={};$('#knob').style.transform='';document.body.classList.toggle('covered',mapOpen);document.body.classList.toggle('map-open',mapOpen);$('#mapButton').textContent=mapOpen?'CLOSE MAP':'MAP';$('#fire').classList.remove('active');$('#toast').textContent=''}$('#mapButton').onclick=toggleMap;
function pause(){if(!running||mapOpen)return;paused=!paused;firing=false;stick={x:0,y:0};keys={};$('#knob').style.transform='';document.body.classList.toggle('covered',paused);$('#overlay').style.display=paused?'flex':'none';$('#title').textContent='PAUSED';$('#intro').textContent='The play test is paused.';$('#start').textContent='Resume'}$('#pause').onclick=pause;$('#start').onclick=()=>{if(running&&paused)pause();else start()};function finish(won){running=false;firing=false;document.body.classList.add('covered');$('#overlay').style.display='flex';$('#title').textContent=won?'EXTRACTION COMPLETE':'SIGNAL LOST';$('#intro').textContent=(won?'You completed the test. ':'You were overrun. ')+kills+' of 12 creatures eliminated.';$('#start').textContent='Restart play test'}
function use(){if(!running||paused||mapOpen)return;let o=objectives[stage];if(o&&distance(player,o)<100){stage++;if(stage===5){finish(true);return}say(['','Security accessed. Locate the power room.','Power restored. Containment unlocked. Recover the laboratory data.','Data and keycard recovered. Reach communications.','Communications restored. Reach the landing pad.'][stage]);updateHUD()}else{const d=nearbyDoor();if(!d){say('Move near a door or the amber objective and press USE.');return}if(stage<d.unlock){say(d.name+' locked. '+lockReason(d));return}if(d.opened&&[player,...creatures.filter(a=>a.hp>0)].some(a=>inside(d,a.x,a.y,a.r+2))){say('Doorway occupied. Step clear before closing.');return}d.opened=!d.opened;creatures.forEach(a=>{a.think=0;a.target=null});say(d.name+' door '+(d.opened?'opened.':'closed.'));updateHUD()}}$('#use').onclick=use;
function reload(){if(!running||paused||mapOpen||reloadTime>0||player.ammo===12)return;reloadTime=1.5;emptyPrompt=false;say('Reloading…');updateHUD()}$('#reload').onclick=reload;
let pointer=null;const stickEl=$('#stick');function stickMove(e){const r=stickEl.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y),radius=r.width*.35;const strength=l<7?0:Math.min(1,l/radius);stick={x:l?x/l*strength:0,y:l?y/l*strength:0};$('#knob').style.transform='translate('+stick.x*radius+'px,'+stick.y*radius+'px)'}stickEl.onpointerdown=e=>{if(!running||paused||mapOpen||pointer!==null)return;e.preventDefault();pointer=e.pointerId;stickEl.setPointerCapture(pointer);stickMove(e)};stickEl.onpointermove=e=>{if(e.pointerId===pointer)stickMove(e)};stickEl.onpointerup=stickEl.onpointercancel=stickEl.onlostpointercapture=e=>{if(e.pointerId!==pointer)return;pointer=null;stick={x:0,y:0};$('#knob').style.transform=''};
let firePointer=null;$('#fire').onpointerdown=e=>{if(!running||paused||mapOpen||firePointer!==null)return;e.preventDefault();firePointer=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);firing=true;$('#fire').classList.add('active')};$('#fire').onpointerup=$('#fire').onpointercancel=$('#fire').onlostpointercapture=e=>{if(e.pointerId!==firePointer)return;firePointer=null;firing=false;$('#fire').classList.remove('active')};
addEventListener('keydown',e=>{let k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(e.repeat&&['m','e','r','escape'].includes(k))return;if(k==='m')toggleMap();else if(k==='e')use();else if(k==='r')reload();else if(k==='escape'){if(mapOpen)toggleMap();else pause()}else keys[k]=true});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused&&!mapOpen)pause()});addEventListener('blur',()=>{keys={};firing=false;stick={x:0,y:0}});
function bodySight(a,b){const d=distance(a,b);for(let i=0;i<=d;i+=8){const f=d?i/d:0;if(!clear(a.x+(b.x-a.x)*f,a.y+(b.y-a.y)*f,a.r))return false}return clear(b.x,b.y,a.r)}
function pathTarget(a){let sx=Math.floor(a.x/TILE),sy=Math.floor(a.y/TILE),gx=Math.floor(player.x/TILE),gy=Math.floor(player.y/TILE);let q=[[gx,gy]],seen=new Set([gx+','+gy]),parent=new Map();for(let i=0;i<q.length;i++){let[x,y]=q[i];if(x===sx&&y===sy)break;for(let[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){let nx=x+dx,ny=y+dy,k=nx+','+ny;if(clear((nx+.5)*TILE,(ny+.5)*TILE,a.r)&&!seen.has(k)){seen.add(k);parent.set(k,[x,y]);q.push([nx,ny])}}}if(sx===gx&&sy===gy)return player;let v=parent.get(sx+','+sy);return v?{x:(v[0]+.5)*TILE,y:(v[1]+.5)*TILE}:null}
function update(dt){clock+=dt;let x=stick.x+(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),y=stick.y+(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),l=Math.hypot(x,y);if(l>.05){player.angle=Math.atan2(y,x);if(l>1){x/=l;y/=l}move(player,x*210*dt,y*210*dt)}cooldown-=dt;player.invuln=Math.max(0,player.invuln-dt);if(reloadTime>0){reloadTime=Math.max(0,reloadTime-dt);if(reloadTime===0){player.ammo=12;emptyPrompt=false;say('Magazine ready: 12 rounds.')}}if((firing||keys[' '])&&cooldown<=0&&reloadTime===0&&player.ammo>0){player.ammo--;cooldown=.13;bullets.push({x:player.x+Math.cos(player.angle)*25,y:player.y+Math.sin(player.angle)*25,vx:Math.cos(player.angle)*800,vy:Math.sin(player.angle)*800,life:1.1});for(let a of creatures)if(distance(a,player)<450)a.active=true}if((firing||keys[' '])&&player.ammo===0&&reloadTime===0&&!emptyPrompt){emptyPrompt=true;say('Magazine empty. Press RELOAD.')}
for(let b of bullets){let steps=Math.ceil(800*dt/8);for(let i=0;i<steps&&b.life>0;i++){b.x+=b.vx*dt/steps;b.y+=b.vy*dt/steps;if(!open(b.x,b.y)){b.life=0;hits.push({x:b.x,y:b.y,life:.15});break}for(let a of creatures)if(a.hp>0&&distance(a,b)<a.r+3){a.hp--;a.active=true;b.life=0;hits.push({x:a.x,y:a.y,life:.2});if(a.hp===0)kills++;break}}b.life-=dt}bullets=bullets.filter(b=>b.life>0);
for(let a of creatures){if(a.hp<=0)continue;let d=distance(a,player);if(d<300&&sight(a,player))a.active=true;if(!a.active)continue;a.think-=dt;if(bodySight(a,player))a.target=player;else if(a.think<=0){a.think=.3;a.target=pathTarget(a)}if(a.target){let dx=a.target.x-a.x,dy=a.target.y-a.y,len=Math.hypot(dx,dy);a.angle=Math.atan2(dy,dx);if(len>3)move(a,dx/len*a.speed*dt,dy/len*a.speed*dt)}if(d<34&&sight(a,player)&&player.invuln<=0){player.hp-=10;player.invuln=.65;if(player.hp<=0){finish(false);return}}}hits.forEach(h=>h.life-=dt);hits=hits.filter(h=>h.life>0);reveal();toastTime-=dt;if(toastTime<=0)$('#toast').textContent='';updateHUD()}
function drawMap(){ctx.fillStyle='#0b1017';ctx.fillRect(0,0,W,H);let s=Math.min((W-80)/(46*TILE),(H-140)/(30*TILE)),ox=(W-46*TILE*s)/2,oy=(H-30*TILE*s)/2+20;ctx.save();ctx.translate(ox,oy);ctx.scale(s,s);for(let k of explored){let [x,y]=k.split(',').map(Number);ctx.fillStyle='#627889';ctx.fillRect(x*TILE,y*TILE,TILE-2,TILE-2)}drawFixtures(true);ctx.font='bold 40px system-ui';ctx.textAlign='center';for(let r of rooms){if(explored.has(Math.floor(r.x+r.w/2)+','+Math.floor(r.y+r.h/2))){ctx.fillStyle='#e1eaf1';ctx.fillText(r.name,(r.x+r.w/2)*TILE,(r.y+r.h/2)*TILE)}}let o=objectives[stage];if(o){ctx.strokeStyle='#ffc56c';ctx.lineWidth=10;ctx.beginPath();ctx.arc(o.x,o.y,42,0,7);ctx.stroke();ctx.fillStyle='#ffc56c';ctx.fillRect(o.x-10,o.y-10,20,20)}ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.fillStyle='#70d4ff';ctx.beginPath();ctx.moveTo(40,0);ctx.lineTo(-25,-25);ctx.lineTo(-25,25);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#dbe8f2';ctx.font='18px system-ui';ctx.textAlign='left';ctx.fillText('MAP · Explored areas only',24,85);ctx.font='14px system-ui';ctx.fillStyle='#aebfcc';ctx.fillText('Blue: you    Amber: current objective    Dark: unexplored    Game paused',24,110)}
function draw(){ctx.fillStyle='#0b1017';ctx.fillRect(0,0,W,H);if(!player)return;if(mapOpen){drawMap();return}ctx.save();ctx.translate(W/2,H/2);ctx.scale(zoom,zoom);ctx.translate(-player.x,-player.y);let minx=Math.floor((player.x-W/zoom/2)/TILE)-1,maxx=Math.ceil((player.x+W/zoom/2)/TILE)+1,miny=Math.floor((player.y-H/zoom/2)/TILE)-1,maxy=Math.ceil((player.y+H/zoom/2)/TILE)+1;for(let y=miny;y<=maxy;y++)for(let x=minx;x<=maxx;x++){if(!floor.has(x+','+y))continue;let fx=x*TILE,fy=y*TILE;ctx.fillStyle=(x+y)%2?'#263440':'#293846';ctx.fillRect(fx,fy,TILE,TILE);ctx.strokeStyle='#334452';ctx.lineWidth=1;ctx.strokeRect(fx,fy,TILE,TILE);for(let[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]])if(!floor.has((x+dx)+','+(y+dy))){ctx.fillStyle='#8293a0';ctx.fillRect(fx+(dx===1?TILE-5:0),fy+(dy===1?TILE-5:0),dx?5:TILE,dy?5:TILE)}}drawFixtures(false);
ctx.textAlign='center';ctx.font='18px system-ui';for(let r of rooms){ctx.fillStyle='#9bb0bf';ctx.fillText(r.name,(r.x+r.w/2)*TILE,(r.y+.65)*TILE)}objectives.forEach((o,i)=>{ctx.fillStyle=i<stage?'#528570':i===stage?'#f0bd68':'#617384';ctx.fillRect(o.x-19,o.y-19,38,38);if(i===stage){ctx.strokeStyle='#f0bd68';ctx.lineWidth=2;ctx.strokeRect(o.x-27,o.y-27,54,54);ctx.fillStyle='#ffdb95';ctx.font='16px system-ui';ctx.fillText('USE',o.x,o.y-38)}});
for(let a of creatures){if(a.hp<=0){ctx.fillStyle='#653737';ctx.fillRect(a.x-10,a.y-8,20,16);continue}ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.angle);ctx.fillStyle=a.active?'#f07872':'#b75b64';ctx.beginPath();ctx.moveTo(21,0);ctx.lineTo(0,-17);ctx.lineTo(-17,0);ctx.lineTo(0,17);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#461f2c';ctx.fillRect(a.x-18,a.y-25,36,4);ctx.fillStyle='#ffb1a6';ctx.fillRect(a.x-18,a.y-25,a.hp*12,4)}ctx.fillStyle='#fff1b0';for(let b of bullets){ctx.beginPath();ctx.arc(b.x,b.y,4,0,7);ctx.fill()}for(let h of hits){ctx.strokeStyle='#ffd284';ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,20*h.life/.2,0,7);ctx.stroke()}
ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.fillStyle=player.invuln>0?'#fff':'#69cdf1';ctx.beginPath();ctx.arc(0,0,16,0,7);ctx.fill();ctx.fillStyle='#e0f8ff';ctx.beginPath();ctx.moveTo(30,0);ctx.lineTo(9,-8);ctx.lineTo(9,8);ctx.closePath();ctx.fill();ctx.restore();ctx.restore()}
function frame(now){let dt=Math.min(.035,(now-last)/1000||0);last=now;if(running&&!paused&&!mapOpen)update(dt);draw();requestAnimationFrame(frame)}reset();requestAnimationFrame(frame);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});

function bindTap(selector,action){const el=$(selector);el.onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();if(!el.disabled)action()};el.onclick=e=>{if(e.detail===0&&!el.disabled)action()};el.oncontextmenu=e=>e.preventDefault()}
bindTap('#reload',reload);bindTap('#use',use);bindTap('#mapButton',toggleMap);bindTap('#pause',pause);bindTap('#start',()=>{if(running&&paused)pause();else start()});
for(const type of ['gesturestart','gesturechange','gestureend'])document.addEventListener(type,e=>e.preventDefault(),{passive:false});
document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});

function drawFixtures(map){
 for(const o of obstacles){for(let y=o.y;y<o.y+o.h;y++)for(let x=o.x;x<o.x+o.w;x++){if(map&&!explored.has(x+','+y))continue;ctx.fillStyle=map?'#ad9374':'#806c52';ctx.fillRect(x*TILE+3,y*TILE+3,TILE-6,TILE-6);ctx.strokeStyle='#c3ad83';ctx.lineWidth=2;ctx.strokeRect(x*TILE+6,y*TILE+6,TILE-12,TILE-12)}if(!map){ctx.textAlign='center';ctx.font='12px system-ui';ctx.fillStyle='#efdbb7';ctx.fillText(o.label,(o.x+o.w/2)*TILE,(o.y+o.h/2)*TILE+4)}}
 for(const d of doors){for(let y=d.y;y<d.y+d.h;y++)for(let x=d.x;x<d.x+d.w;x++){if(map&&!explored.has(x+','+y))continue;ctx.strokeStyle=d.opened?'#66bca1':stage<d.unlock?'#e37670':'#e3ba6c';ctx.lineWidth=4;if(d.opened){ctx.strokeRect(x*TILE+4,y*TILE+4,TILE-8,TILE-8)}else{ctx.fillStyle=stage<d.unlock?'#6f393b':'#665a3f';ctx.fillRect(x*TILE,y*TILE,TILE,TILE);ctx.strokeRect(x*TILE+4,y*TILE+4,TILE-8,TILE-8)}}if(!map){ctx.textAlign='center';ctx.font='14px system-ui';ctx.fillStyle='#e4edf3';ctx.fillText(d.opened?'OPEN':stage<d.unlock?'LOCKED':'DOOR',(d.x+d.w/2)*TILE,(d.y+d.h/2)*TILE+4)}}
}
